CREATE TABLE IF NOT EXISTS user_readings (
	id SERIAL PRIMARY KEY,
	user_id UUID REFERENCES users(id) ON DELETE CASCADE,
	reading_id INTEGER NOT NULL REFERENCES readings(id) ON DELETE CASCADE,
	is_reading BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

	-- Foreign key constraint


CREATE TABLE IF NOT EXISTS user_evaluations (
    id SERIAL PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    evaluation_id INTEGER NOT NULL,
    attempt INTEGER DEFAULT 1 NOT NULL,
    percentage_grade DOUBLE PRECISION DEFAULT 0 NOT NULL,
    time_duration INTEGER DEFAULT 0 NOT NULL,
    point INTEGER DEFAULT 0 NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


